title: shomy
description:
  Musician, gamer and developer.
  Currently making my dream game 🎮.
baseurl: ""
url: "https://shomy.is-a.dev"
twitter_username: shomykohai
github_username:  shomykohai

theme: jekyll-dash
plugins:
  - jekyll-feed
  - jekyll/tagging
  - jekyll-paginate-v2

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/article/:title"

# For compatibility with dash's pagination.html
paginate_path: /page/:num/

pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 5
  permalink: 'page/:num/'
  title: ':title - page'
  sort_field: 'date'
  sort_reverse: true


tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

routes: [
  blog,
  docs
]

projects: [
  https://github.com/shomykohai/quest-system,
  https://github.com/shomykohai/godot-keyring,
  https://github.com/shomykohai/askitsu,
  https://github.com/shomykohai/kitsu-bot
]

sass:
  style: compressed

sitemap:
  banned: []
  allowed: [
    html
  ]

dash:
  date_format: "%b %-d, %Y"

  social_links:
    - url: https://github.com/shomykohai
      icon: github
      color: purple
    - url: https://twitter.com/shomykohai
      icon: twitter
      color: cyan
    - url: https://shomy.bsky.social/
      icon: bluesky
      fa: true
      color: cyan
    - url: https://shomy.is-a.dev/feed.xml
      fa: true # Font Awesome Free
      icon: rss
      color: orange

  show_author: true
  github-username: shomykohai
  avatar_source: github
